pipeline {
  agent { label 'conan_pipe_worker'}
  parameters {
    string(name: 'Versions', defaultValue: 'v1, v2, v3')
    string(name: 'Architectures', defaultValue: 'release, debug')
    string(name: 'Build_types', defaultValue: 'x86_64, i686')
  }
  stages {
    stage('Build') {
      script {
        p = load '../functions.groovy'
        p.build(${params.Versions}, ${params.Architectures}, ${params.Build_types})
        p.upload("http://internet.com")
      }
    }
  }
}
